### ISSUE TITLE
Offline-capabilities for API-calls

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#1]
Information retrieved from the backend should be cached.

**Comment by ahus1** [comment]
@sippsack @ascheman @steffchep - this now ready for a first review. I've moved it to the tab "To Review" in the project view.

**Comment by sippsack** [comment]
Looks good for me.

But how about conditional loading with etag? How can we integrate "if-none-match" header?

**Comment by ahus1** [comment]
@sippsack - I suppose we will just rely on the browser to cache the response. The browser already re-sends the etag automatically. But the server (i.e. https://latest.dukecon.org/javaland/2017/rest/conferences/javaland2017/) doesn't respond with 304 at the moment; you can check this if you manually load the link. 

This seems to be a bug in the server. I'll open a ticket for that.

**Comment by ahus1** [comment]
@sippsack - regarding your comment in the other ticket, will you review this ticket and approve it? If not, please comment.

**Comment by sippsack** [comment]
it is fine for me.

@ascheman, @steffchep : Please also have a look because of knowledge transfer.

**Comment by sippsack** [comment]
@ahus1: the caching with etag seems to work when requesting a localhost rest backend:

![image](https://user-images.githubusercontent.com/413426/29537725-0e6cbd76-86c3-11e7-85df-c42a6957bec7.png)
![image](https://user-images.githubusercontent.com/413426/29537762-3cb2e7dc-86c3-11e7-9f1c-b8026211bcce.png)

But init.json still return 200, because no "If-None-Match" header was sent:

![image](https://user-images.githubusercontent.com/413426/29537846-8c09e9fc-86c3-11e7-8715-2e93434260ea.png)

No idea why this behaves differently.
