### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_pwa#14]
Add search functionality for events and speakers.

**Comment by ahus1** [comment]
@sippsack - pushed a change to fix the back button and responsive tool bar.

On the phone we discussed that the search should work in addition to the filters. I think we should first keep it "as is" with the existing functionality (and like you implemented it) -- any change in functionality should be part of a UX-design workshop.

**Comment by sippsack** [comment]
TODO:

* search box is always in header, not only for talks and speakers
* searching for talks should hide days without search results

**Comment by ahus1** [comment]
@sippsack - I tried out the current status of the search. These are my recorded experiences:

When the search leads to no result and I choose "reset", everything is reset, both filters and the search. The message (and the action) should only reset the search when the result is caused by a search (as we discussed in the current implementation the search has precedence over the filters)

When I click on a search result and go to the talk details, and the go back, the search term is gone (as it is reset on each navigation) - this surprised me and from a UX perspective surprises are bad. I don't understand why you've chosen to reset the search on every navigation. 

Something I said on the phone to @ascheman: I would like to focus on making the pwa app feature complete compared to the old app without changing too much (or anything) in the user experience. This will allow us to switch over to the new app rather soon. This includes postponing ideas like "searching for talks should hide days without search results".

Making changes to the functionality leads to lots of discussions and trial-and-error, and the old app will live longer than we all want it to live. I would prefer an user experience workshop to discuss and evaluate changes before putting them down into code. This would allow us to get the know-how in one place, and evaluation options before investing time in coding it.

**Comment by sippsack** [comment]
@ahus1: I understand your concerns and I wasn't aware, that we will realize the pwa app without changing anything. Then I have to rebuild the search functionality, search and filter has to be seperated. I also just figured out, that the filtering doesn't work at all at the moment because of the precedence of the search.

I did reset the search term on each navigation because the search term was still visible after switching the route. I wasn't aware of returning from detail page. In the old app, each menu entry refers to a separate page and search was only available on the talk page. So, the old app hasn't to handle this behavior at the moment.

What about the speaker search? You can now also search for speakers on the speaker page. This is definitely a new behavior. Shall I remove it?

**Comment by sippsack** [comment]
@ahus1: ready for review, now it looks nearly the same as the old one

**Comment by ahus1** [comment]
@sippsack - review complete: 
* this condition for the time cell used "this." as a prefix for variables. This didn't work reliably for me - you shouldn't prefix this.
* I compared the functionality of the old dukecon with the new dukecon: on the talks page the search works on all events, not only on the events of the current day. I suppose that was the reason why the days disappear together with the time. I change it to filter all talks. 
* the speakers and talksgrid page now send a search.init event to the search to request the status whenever they initialize. Due to this the you can enter a search term in talksgrid that will be effective when you switch to the speakers page.
