### ISSUE TITLE
Update Package dependencies and add package-lock.json to build

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#32]
Latest NPM creates package-lock.json to allow to pin certain versions to a build (cf. https://dukecon.slack.com/archives/C1K58BTN1/p1514454111000144). 
We should actively maintain this file and update packages to desired (and tested) versions. 
For the time being the file will be ignored.

**Comment by ahus1** [comment]
@steffchep - there is now a npm-shrinkwrap.json that locks the version numbers of used packages. I avoid to use package-lock.json because it needs to contain the full URL of a package, and this might point to a local npm mirror.

@steffchep / @sippsack: please run _npm install_ after this change. Maybe even delete your _node_modules_ folder.
